- name: remove default login setting
  become: yes
  file:
    path: /etc/pam.d/login
    state: absent

- name: copy custom login setting
  become: yes
  copy:
    src: login
    dest: /etc/pam.d/login
    owner: root
    group: root
    mode: 0644

- name: remove default pwquality
  become: yes
  file:
    path: /etc/security/pwquality.conf
    state: absent

- name: copy custom pwquality
  become: yes
  copy:
    src: pwquality.conf
    dest: /etc/security/pwquality.conf
    owner: root
    group: root
    mode: 0644

- name: remove default system-auth
  become: yes
  file:
    path: /etc/pam.d/system-auth
    state: absent

- name: copy custom system-auth
  become: yes
  copy:
    src: system-auth
    dest: /etc/pam.d/system-auth
    owner: root
    group: root
    mode: 0644

- name: mod hosts file 600
  become: yes
  file:
    path: /etc/hosts
    mode: 0600

- name: disable anonymous ftp
  become: yes
  user:
    name: ftp
    state: absent

- name: remove default login.defs
  become: yes
  file:
    path: /etc/login.defs
    state: absent

- name: copy custom login.defs
  become: yes
  copy:
    src: login.defs
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 0644

- name: remove default profile
  become: yes
  file:
    path: /etc/profile
    state: absent

- name: copy custom profile change session timeout, umask, history log
  become: yes
  copy:
    src: profile
    dest: /etc/profile
    owner: root
    group: root
    mode: 0644
  notify:
    - update /etc/profile

- name: mod at.deny file 640
  become: yes
  file:
    path: "/etc/at.deny"
    mode: 0640

- name: install latest versions for CVE
  become: yes
  ignore_errors: yes
  yum:
    name:
      - nss-pem
      - libsss_idmap
      - libsss_nss_idmap
      - sssd-client
      - curl
      - libcurl
      - binutils
      - glibc*
      - libcrypt
      - krb5-libs
      - kernel
      - kernel-tools
      - wget
    state: latest
    update_only: yes
