- name: install OpenJDK 8
  become: yes
  yum:
    name: java-1.8.0-openjdk-devel
    state: latest

- name: correct java version selected
  become: yes
  alternatives:
    name: java
    path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.amzn2.x86_64/jre/bin/java
